# Мы используем compose чтобы показать Round Robin DNS
services:
  dnsmasq:
    build: ./dns
    container_name: search-dnsmasq
    ports:
      - "8053:53/udp"
      - "8053:53/tcp"
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - dns-logs:/var/log
    networks:
      dns_net:
        ipv4_address: 172.30.0.10
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
      - 8.8.8.8

  nginx-dc1:
    image: nginx:alpine
    container_name: search-nginx-dc1
    ports:
      - "8081:80"
    networks:
      dns_net:
        ipv4_address: 172.30.0.11
    restart: unless-stopped

  nginx-dc2:
    image: nginx:alpine
    container_name: search-nginx-dc2
    ports:
      - "8082:80"
    networks:
      dns_net:
        ipv4_address: 172.30.0.12
    restart: unless-stopped

  nginx-dc3:
    image: nginx:alpine
    container_name: search-nginx-dc3
    ports:
      - "8083:80"
    networks:
      dns_net:
        ipv4_address: 172.30.0.13
    restart: unless-stopped

networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  dns-logs:
